server:   #端口
  servlet:
    context-path:
  port: 8080

id: 2     #测试用
userName: EkKo
loginName: root
passWord: 123

spring:
  datasource:
    username: root
    password: 401120719
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/gezhi?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false&serverTimezone=GMT%2B8
mybatis:
  mapper-locations: classpath:sqlmap/LoginMapper.xml
  type-aliases-package: com.gezhi.demo.pojo.User
